<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PMLDVBALAJID" failures="1" tests="5" name="PetTest" time="6.015" errors="0" timestamp="2024-04-02T16:16:26 IST">
  <testcase classname="api.test.UserTests2" name="testFailedTest" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at api.test.UserTests2.testFailedTest(UserTests2.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testFailedTest -->
  <testcase classname="api.test.UserTests2" name="test_post_User" time="2.18"/>
  <testcase classname="api.test.UserTests2" name="getUserByName" time="1.027"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="1.051"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByUserName" time="1.029"/>
</testsuite> <!-- PetTest -->
